// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihhmdkxcttbuejbplowb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloaG1ka3hjdHRidWVqYnBsb3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwOTUzNzQsImV4cCI6MjA1NTY3MTM3NH0.eAMoDCQ-InU6DqY7j6ZDP2yPV0TMGDcYk0fKw_MC3vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);