// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
// import type { Database } from './types';

const SUPABASE_URL = "https://upnhxshwzpbcfmumclwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwbmh4c2h3enBiY2ZtdW1jbHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTAyMzgsImV4cCI6MjA1Nzk2NjIzOH0.hVFRmd9UtrVPuufJawg6aJGcVQoxSVzKsBrz3_4lkCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
